import { useEffect, useMemo } from "react";
import { useQuery } from "@tanstack/react-query";
import { useForm } from "react-hook-form";
import type { RegisterOptions } from "react-hook-form";
import { Link, useNavigate, useParams } from "react-router-dom";
import { Button } from "../../components/ui/Button";
import { Card } from "../../components/ui/Card";
import { FormActions } from "../../components/forms/FormActions";
import { FormField } from "../../components/forms/FormField";
import { FormSelect } from "../../components/forms/FormSelect";
import { FormTextArea } from "../../components/forms/FormTextArea";
import { ErrorState } from "../../components/ui/ErrorState";
import { LoadingState } from "../../components/ui/LoadingState";
import { useCrudResource, useCrudService } from "../../hooks/useCrudResource";
import { moduleRoutes } from "../modules/moduleRegistry";
import { useDataverseClient } from "../../services/dataverse/DataverseContext";
import type { BaseRecord, ModuleConfig, ModuleFormField } from "../../types/entities";

export function EntityFormPage<TRecord extends BaseRecord>({
  moduleConfig,
}: {
  moduleConfig: ModuleConfig<TRecord>;
}) {
  const navigate = useNavigate();
  const { id } = useParams();
  const isEditMode = Boolean(id);
  const client = useDataverseClient();
  const service = useCrudService(moduleConfig);
  const { createMutation, updateMutation } = useCrudResource(moduleConfig);
  const formFields = moduleConfig.formFields ?? [];
  const visibleFormFields = useMemo(
    () => formFields.filter((field) => !field.hidden),
    [formFields],
  );
  const autoGeneratedFieldCount = useMemo(
    () => formFields.filter((field) => field.autoGenerate).length,
    [formFields],
  );
  const lookupFields = useMemo(
    () => visibleFormFields.filter((field) => field.type === "lookup" && field.lookup),
    [visibleFormFields],
  );
  const lookupModules = useMemo(
    () =>
      lookupFields.reduce<Record<string, ModuleConfig<BaseRecord>>>((accumulator, field) => {
        const targetModule = moduleRoutes.find((route) => route.key === field.lookup?.moduleKey);
        if (targetModule && field.lookup) {
          accumulator[field.key] = targetModule;
        }
        return accumulator;
      }, {}),
    [lookupFields],
  );

  const form = useForm<Record<string, string | number>>({
    defaultValues: visibleFormFields.reduce<Record<string, string | number>>((accumulator, field) => {
      accumulator[field.key] = "";
      return accumulator;
    }, {}),
  });

  const detailQuery = useQuery({
    queryKey: [moduleConfig.key, "edit", id],
    queryFn: () => service.getById(id ?? ""),
    enabled: isEditMode,
  });

  const lookupOptionsQuery = useQuery({
    queryKey: [moduleConfig.key, "lookup-options", ...lookupFields.map((field) => field.key)],
    queryFn: async () => {
      const optionEntries = await Promise.all(
        lookupFields.map(async (field) => {
          const targetModule = lookupModules[field.key];

          if (!targetModule) {
            return [field.key, []] as const;
          }

          const response = await client.request<{ value: Array<Record<string, unknown>> }>(
            `${targetModule.entitySetName}?$select=${targetModule.primaryIdField},${String(
              targetModule.columns[0]?.key ?? targetModule.titleField,
            )}`,
          );

          const labelKey = String(targetModule.columns[0]?.key ?? targetModule.titleField);

          return [
            field.key,
            response.value.map((item) => ({
              value: String(item[targetModule.primaryIdField] ?? ""),
              label: String(item[labelKey] ?? "Unnamed record"),
            })),
          ] as const;
        }),
      );

      return Object.fromEntries(optionEntries);
    },
    enabled: lookupFields.length > 0,
  });

  useEffect(() => {
    if (detailQuery.data) {
      const rawRecord = detailQuery.data as unknown as Record<string, unknown>;
      const nextValues = visibleFormFields.reduce<Record<string, string | number>>((accumulator, field) => {
        const rawValue = rawRecord[field.key];
        if (field.type === "number") {
          accumulator[field.key] =
            typeof rawValue === "number" ? rawValue : rawValue ? Number(rawValue) : "";
        } else {
          accumulator[field.key] = rawValue ? String(rawValue) : "";
        }
        return accumulator;
      }, {});

      form.reset(nextValues);
    }
  }, [detailQuery.data, form, visibleFormFields]);

  const onSubmit = form.handleSubmit(async (values) => {
    const payload = formFields.reduce<Record<string, unknown>>((accumulator, field) => {
      if (field.autoGenerate && !isEditMode) {
        accumulator[field.key] = buildGeneratedBusinessId(field.autoGenerate.prefix);
        return accumulator;
      }

      if (field.hidden) {
        return accumulator;
      }

      const value = values[field.key];
      if (field.type === "lookup" && field.lookup) {
        const selectedId = typeof value === "string" ? value.trim() : String(value ?? "").trim();
        if (selectedId) {
          const targetModule = lookupModules[field.key];
          if (targetModule) {
            accumulator[`${field.lookup.bindKey}@odata.bind`] = `/${targetModule.entitySetName}(${selectedId})`;
          }
        } else if (isEditMode) {
          accumulator[`${field.lookup.bindKey}@odata.bind`] = null;
        }
        return accumulator;
      }

      if (field.type === "number") {
        const normalizedValue =
          typeof value === "number"
            ? value
            : typeof value === "string" && value.trim().length > 0
              ? Number(value)
              : undefined;

        if (normalizedValue === undefined || Number.isNaN(normalizedValue)) {
          if (isEditMode) {
            accumulator[field.key] = null;
          }
          return accumulator;
        }

        accumulator[field.key] = normalizedValue;
      } else {
        const normalizedValue = typeof value === "string" ? value.trim() : String(value ?? "").trim();

        if (!normalizedValue) {
          if (isEditMode) {
            accumulator[field.key] = null;
          }
          return accumulator;
        }

        accumulator[field.key] = normalizedValue;
      }
      return accumulator;
    }, {});

    if (isEditMode && id) {
      await updateMutation.mutateAsync({ id, values: payload as Partial<TRecord> });
    } else {
      await createMutation.mutateAsync(payload as Partial<TRecord>);
    }

    navigate(`/${moduleConfig.path}`);
  });

  if (isEditMode && detailQuery.isLoading) {
    return <LoadingState label={`Loading ${moduleConfig.singularLabel.toLowerCase()} form...`} />;
  }

  if (isEditMode && detailQuery.isError) {
    return (
      <ErrorState
        message={detailQuery.error instanceof Error ? detailQuery.error.message : "Unable to load record for editing."}
      />
    );
  }

  return (
    <div className="page">
      <div className="page__header">
        <div>
          <span className="eyebrow">{isEditMode ? `Edit ${moduleConfig.singularLabel}` : `Create ${moduleConfig.singularLabel}`}</span>
          <h1>{isEditMode ? `Edit ${moduleConfig.singularLabel}` : `New ${moduleConfig.singularLabel}`}</h1>
        </div>
      </div>

      <Card title="Record Form" subtitle={getFormSubtitle(moduleConfig.key)}>
        {autoGeneratedFieldCount > 0 ? (
          <p className="page__caption">
            {getAutoGeneratedMessage(moduleConfig)}
          </p>
        ) : null}
        <form className="form-grid" onSubmit={onSubmit}>
          {visibleFormFields.map((field) => {
            const error = form.formState.errors[field.key];
            const rules = buildFieldRules(field);

            if (field.type === "textarea") {
              return (
                <FormTextArea
                  key={field.key}
                  label={field.label}
                  rows={4}
                  placeholder={field.placeholder}
                  description={field.description}
                  requiredIndicator={field.required}
                  {...form.register(field.key, rules)}
                  error={error?.message ? String(error.message) : undefined}
                />
              );
            }

            if (field.options && field.options.length > 0) {
              return (
                <FormSelect
                  key={field.key}
                  label={field.label}
                  options={field.options}
                  placeholder={field.placeholder}
                  description={field.description}
                  requiredIndicator={field.required}
                  {...form.register(field.key, rules)}
                  error={error?.message ? String(error.message) : undefined}
                />
              );
            }

            if (field.type === "lookup") {
              return (
                <FormSelect
                  key={field.key}
                  label={field.label}
                  options={lookupOptionsQuery.data?.[field.key] ?? []}
                  placeholder={field.placeholder ?? `Select ${field.label.toLowerCase()}`}
                  description={field.description}
                  requiredIndicator={field.required}
                  {...form.register(field.key, rules)}
                  error={error?.message ? String(error.message) : undefined}
                />
              );
            }

            return (
              <FormField
                key={field.key}
                label={field.label}
                type={field.type === "number" ? "number" : field.type}
                step={field.step ?? (field.type === "number" ? "any" : undefined)}
                min={field.min}
                max={field.max}
                placeholder={field.placeholder}
                description={field.description}
                requiredIndicator={field.required}
                {...form.register(field.key, rules)}
                error={error?.message ? String(error.message) : undefined}
              />
            );
          })}

          <FormActions>
            <Button type="submit" disabled={createMutation.isPending || updateMutation.isPending}>
              {isEditMode ? "Save changes" : `Create ${moduleConfig.singularLabel}`}
            </Button>
            <Link className="text-link" to={`/${moduleConfig.path}`}>
              Cancel
            </Link>
          </FormActions>
        </form>
      </Card>
    </div>
  );
}

function buildGeneratedBusinessId(prefix: string) {
  const stamp = new Date().toISOString().slice(0, 10).replace(/-/g, "");
  const suffix = crypto.randomUUID().slice(0, 6).toUpperCase();
  return `PAES-${prefix}-${stamp}-${suffix}`;
}

function buildFieldRules(field: ModuleFormField): RegisterOptions {
  const rules: RegisterOptions = {};

  if (!field) {
    return rules;
  }

  if (field.required) {
    rules.required = `${field.label} is required`;
  }

  if (field.minLength) {
    rules.minLength = {
      value: field.minLength,
      message: `${field.label} must be at least ${field.minLength} characters`,
    };
  }

  if (field.maxLength) {
    rules.maxLength = {
      value: field.maxLength,
      message: `${field.label} must be ${field.maxLength} characters or fewer`,
    };
  }

  if (field.pattern) {
    rules.pattern = {
      value: new RegExp(field.pattern),
      message: field.patternMessage ?? `${field.label} format is invalid`,
    };
  }

  if (field.type === "number") {
    rules.setValueAs = (value: unknown) => {
      if (value === "" || value === null || value === undefined) {
        return undefined;
      }

      const normalized = Number(value);
      return Number.isNaN(normalized) ? undefined : normalized;
    };

    if (typeof field.min === "number") {
      rules.min = {
        value: field.min,
        message: `${field.label} must be at least ${field.min}`,
      };
    }

    if (typeof field.max === "number") {
      rules.max = {
        value: field.max,
        message: `${field.label} must be no more than ${field.max}`,
      };
    }
  }

  return rules;
}

function getFormSubtitle(moduleKey: string) {
  const subtitles: Record<string, string> = {
    demand: "Capture client demand, hiring requirements, and expected commercial value.",
    supply: "Record available talent supply, readiness expectations, and partner alignment.",
    readiness: "Assess whether supply is ready to move forward for deployment.",
    partners: "Maintain partner information, ownership, and operational contacts.",
    deployments: "Track deployment planning, launch progress, and placement outcomes.",
    learners: "Maintain learner profiles, linked training, and follow-up information.",
    courses: "Define course offerings, delivery setup, and pricing.",
    payments: "Capture commercial transactions, revenue source, and payment follow-up.",
    events: "Plan and track events at summary level, with optional participant-level registration later.",
    "event-registrations": "Capture participant-level attendance or payment details only when detailed event tracking is needed.",
    certifications: "Track certification progress, costs, revenue, and demand linkage.",
  };

  return subtitles[moduleKey] ?? "Capture and maintain operational information for this area.";
}

function getAutoGeneratedMessage<TRecord extends BaseRecord>(moduleConfig: ModuleConfig<TRecord>) {
  const messages: Record<string, string> = {
    demand: "Demand reference numbers are generated automatically when you save.",
    supply: "Supply reference numbers are generated automatically when you save.",
    readiness: "Readiness reference numbers are generated automatically when you save.",
    partners: "Partner reference numbers are generated automatically when you save.",
    deployments: "Deployment reference numbers are generated automatically when you save.",
    learners: "Learner reference numbers are generated automatically when you save.",
    courses: "Course reference numbers are generated automatically when you save.",
    payments: "Payment reference IDs are generated automatically when you save.",
    events: "Event reference numbers are generated automatically when you save.",
    "event-registrations": "Registration reference numbers are generated automatically when you save.",
    certifications: "Certification reference numbers are generated automatically when you save.",
  };

  return messages[moduleConfig.key] ?? `Reference numbers for this ${moduleConfig.singularLabel.toLowerCase()} are generated automatically when you save.`;
}
