import type { DemandRecord, ModuleConfig, SupplyRecord, BaseRecord } from "../../types/entities";

function buildModule<TRecord extends BaseRecord>(
  moduleConfig: ModuleConfig<TRecord>,
): ModuleConfig<TRecord> {
  return moduleConfig;
}

const commonStatusOptions = [
  { label: "Open", value: "Open" },
  { label: "In Progress", value: "In Progress" },
  { label: "Closed", value: "Closed" },
];

const readinessStatusOptions = [
  { label: "Not Ready", value: "Not Ready" },
  { label: "In Progress", value: "In Progress" },
  { label: "Ready", value: "Ready" },
];

const yesNoPartialOptions = [
  { label: "Yes", value: "Yes" },
  { label: "No", value: "No" },
  { label: "Partial", value: "Partial" },
];

export const demandModule = buildModule<DemandRecord>({
  key: "demand",
  label: "Demand Management",
  singularLabel: "Demand",
  path: "demand",
  icon: "briefcase",
  tableName: "PAES Demand",
  entitySetName: "paes_paesdemands",
  primaryIdField: "paes_paesdemandid",
  titleField: "name",
  columns: [
    { key: "paes_demandname" as keyof DemandRecord, label: "Demand" },
    { key: "paes_sector" as keyof DemandRecord, label: "Sector" },
    { key: "paes_region" as keyof DemandRecord, label: "Region" },
    { key: "paes_numberofseats" as keyof DemandRecord, label: "Seats" },
    { key: "paes_status" as keyof DemandRecord, label: "Status" },
  ],
  detailFields: [
    { key: "paes_demandname" as keyof DemandRecord, label: "Demand Name" },
    { key: "paes_clientname" as keyof DemandRecord, label: "Client Name" },
    { key: "paes_sector" as keyof DemandRecord, label: "Sector" },
    { key: "paes_region" as keyof DemandRecord, label: "Region" },
    { key: "paes_numberofseats" as keyof DemandRecord, label: "Requested Seats" },
    { key: "paes_expectedrevenue" as keyof DemandRecord, label: "Expected Revenue" },
    { key: "paes_status" as keyof DemandRecord, label: "Status" },
  ],
  formFields: [
    { key: "paes_demandid", label: "Demand ID", hidden: true, autoGenerate: { prefix: "DMD" } },
    {
      key: "paes_demandname",
      label: "Demand Name",
      required: true,
      minLength: 5,
      maxLength: 120,
      placeholder: "Contact centre talent wave - Q3",
      description: "Use a short business title that leadership can recognize in reports.",
    },
    {
      key: "paes_clientname",
      label: "Client Name",
      required: true,
      minLength: 2,
      maxLength: 120,
      placeholder: "Client, employer, or strategic partner",
    },
    { key: "paes_sector", label: "Sector", required: true, minLength: 2, maxLength: 80, placeholder: "ICT, healthcare, logistics, hospitality" },
    { key: "paes_region", label: "Region", required: true, minLength: 2, maxLength: 80, placeholder: "Country, city, or delivery region" },
    { key: "paes_skillcategory", label: "Skill Category", required: true, minLength: 2, maxLength: 80, placeholder: "Customer support, software QA, caregiving" },
    {
      key: "paes_requiredskills",
      label: "Required Skills",
      type: "textarea",
      required: true,
      minLength: 10,
      placeholder: "List the critical skills, tools, or language requirements for deployment.",
    },
    {
      key: "paes_requiredexperience",
      label: "Required Experience",
      required: true,
      minLength: 2,
      maxLength: 80,
      placeholder: "Graduate, 1-2 years, senior specialist",
    },
    {
      key: "paes_requiredqualifications",
      label: "Required Qualifications",
      required: true,
      minLength: 2,
      maxLength: 120,
      placeholder: "Degree, diploma, TVET, vendor certification",
    },
    {
      key: "paes_certificationrequired",
      label: "Certification Required",
      required: true,
      options: [
        { label: "Yes", value: "Yes" },
        { label: "No", value: "No" },
      ],
      placeholder: "Select requirement",
    },
    {
      key: "paes_numberofseats",
      label: "Number of Seats",
      type: "number",
      required: true,
      min: 1,
      step: 1,
      placeholder: "0",
    },
    { key: "paes_expectedstartdate", label: "Expected Start Date", type: "date", required: true, description: "Use the planned mobilization or go-live date." },
    {
      key: "paes_expectedrevenue",
      label: "Expected Revenue",
      type: "number",
      min: 0,
      step: 0.01,
      placeholder: "0.00",
      description: "Enter the projected commercial value for this demand.",
    },
    { key: "paes_status", label: "Status", required: true, options: commonStatusOptions, placeholder: "Select status" },
    {
      key: "paes_notes",
      label: "Notes",
      type: "textarea",
      maxLength: 500,
      placeholder: "Add client context, mobilization notes, commercial assumptions, or dependencies.",
    },
  ],
});

export const supplyModule = buildModule<SupplyRecord>({
  key: "supply",
  label: "Supply / Talent Management",
  singularLabel: "Supply Profile",
  path: "supply",
  icon: "users",
  tableName: "PAES Supply",
  entitySetName: "paes_paessupplies",
  primaryIdField: "paes_paessupplyid",
  titleField: "name",
  columns: [
    { key: "paes_supplyname" as keyof SupplyRecord, label: "Supply" },
    { key: "paes_candidatename" as keyof SupplyRecord, label: "Candidate" },
    { key: "paes_skillcategory" as keyof SupplyRecord, label: "Skill Category" },
    { key: "paes_region" as keyof SupplyRecord, label: "Region" },
    { key: "paes_status" as keyof SupplyRecord, label: "Status" },
  ],
  detailFields: [
    { key: "paes_supplyname" as keyof SupplyRecord, label: "Supply Name" },
    { key: "paes_candidatename" as keyof SupplyRecord, label: "Candidate Name" },
    { key: "paes_region" as keyof SupplyRecord, label: "Region" },
    { key: "paes_skillcategory" as keyof SupplyRecord, label: "Skill Category" },
    { key: "paes_experiencelevel" as keyof SupplyRecord, label: "Experience Level" },
    { key: "paes_qualificationstatus" as keyof SupplyRecord, label: "Qualification Status" },
    { key: "paes_certificationstatus" as keyof SupplyRecord, label: "Certification Status" },
    { key: "paes_availabilitystatus" as keyof SupplyRecord, label: "Availability Status" },
    { key: "paes_expectedreadinessdate" as keyof SupplyRecord, label: "Expected Readiness Date" },
    { key: "paes_status" as keyof SupplyRecord, label: "Status" },
  ],
  formFields: [
    { key: "paes_supplyid", label: "Supply ID", hidden: true, autoGenerate: { prefix: "SUP" } },
    {
      key: "paes_supplyname",
      label: "Supply Name",
      required: true,
      minLength: 5,
      maxLength: 120,
      placeholder: "Arabic customer support cohort",
      description: "Use a supply or cohort name that operations can track easily.",
    },
    {
      key: "_paes_linkeddemand_value",
      label: "Linked Demand",
      type: "lookup",
      required: true,
      placeholder: "Select demand",
      lookup: { moduleKey: "demand", bindKey: "paes_LinkedDemand" },
    },
    {
      key: "_paes_partner_value",
      label: "Partner",
      type: "lookup",
      required: true,
      placeholder: "Select partner",
      lookup: { moduleKey: "partners", bindKey: "paes_Partner" },
    },
    {
      key: "paes_candidatename",
      label: "Candidate Name",
      required: true,
      minLength: 2,
      maxLength: 120,
      placeholder: "Candidate, cohort, or talent pool name",
    },
    { key: "paes_skillcategory", label: "Skill Category", required: true, minLength: 2, maxLength: 80, placeholder: "Data annotation, digital sales, caregiving" },
    {
      key: "paes_skillssummary",
      label: "Skills Summary",
      type: "textarea",
      minLength: 10,
      maxLength: 500,
      placeholder: "Summarize language ability, tools, technical strengths, and employability indicators.",
    },
    { key: "paes_region", label: "Region", required: true, minLength: 2, maxLength: 80, placeholder: "Country, city, or delivery region" },
    { key: "paes_experiencelevel", label: "Experience Level", required: true, minLength: 2, maxLength: 80, placeholder: "Entry level, junior, experienced" },
    { key: "paes_qualificationstatus", label: "Qualification Status", required: true, options: yesNoPartialOptions, placeholder: "Select qualification status" },
    { key: "paes_certificationstatus", label: "Certification Status", required: true, options: yesNoPartialOptions, placeholder: "Select certification status" },
    {
      key: "paes_availabilitystatus",
      label: "Availability Status",
      required: true,
      options: [
        { label: "Available", value: "Available" },
        { label: "Committed", value: "Committed" },
        { label: "Pipeline", value: "Pipeline" },
      ],
      placeholder: "Select availability",
    },
    { key: "paes_expectedreadinessdate", label: "Expected Readiness Date", type: "date", required: true },
    { key: "paes_status", label: "Status", required: true, options: commonStatusOptions, placeholder: "Select status" },
    {
      key: "paes_notes",
      label: "Notes",
      type: "textarea",
      maxLength: 500,
      placeholder: "Capture sourcing assumptions, talent risk, mobility constraints, or partner remarks.",
    },
  ],
});

export const moduleRoutes: Array<ModuleConfig<BaseRecord>> = [
  demandModule as ModuleConfig<BaseRecord>,
  supplyModule as ModuleConfig<BaseRecord>,
  buildModule<BaseRecord>({
    key: "readiness",
    label: "Readiness",
    singularLabel: "Readiness Record",
    path: "readiness",
    icon: "graduation",
    tableName: "PAES Readiness",
    entitySetName: "paes_paesreadinesses",
    primaryIdField: "paes_paesreadinessid",
    titleField: "name",
    columns: [
      { key: "paes_readinessname" as keyof BaseRecord, label: "Readiness" },
      { key: "paes_readinessstatus" as keyof BaseRecord, label: "Readiness Status" },
      { key: "paes_skillsmatch" as keyof BaseRecord, label: "Skills Match" },
      { key: "paes_experiencematch" as keyof BaseRecord, label: "Experience Match" },
      { key: "paes_trainingstatus" as keyof BaseRecord, label: "Training Status" },
    ],
    detailFields: [
      { key: "paes_readinessname" as keyof BaseRecord, label: "Readiness Name" },
      { key: "paes_readinessid" as keyof BaseRecord, label: "Readiness ID" },
      { key: "paes_readinessstatus" as keyof BaseRecord, label: "Readiness Status" },
      { key: "paes_skillsmatch" as keyof BaseRecord, label: "Skills Match" },
      { key: "paes_experiencematch" as keyof BaseRecord, label: "Experience Match" },
      { key: "paes_qualificationstatus" as keyof BaseRecord, label: "Qualification Status" },
      { key: "paes_certificationstatus" as keyof BaseRecord, label: "Certification Status" },
      { key: "paes_trainingstatus" as keyof BaseRecord, label: "Training Status" },
      { key: "paes_keyrequirementsmet" as keyof BaseRecord, label: "Key Requirements Met" },
      { key: "paes_dateupdated" as keyof BaseRecord, label: "Date Updated" },
      { key: "paes_notes" as keyof BaseRecord, label: "Notes" },
    ],
    formFields: [
      { key: "paes_readinessid", label: "Readiness ID", hidden: true, autoGenerate: { prefix: "RDY" } },
      {
        key: "paes_readinessname",
        label: "Readiness Name",
        required: true,
        minLength: 5,
        maxLength: 120,
        placeholder: "Readiness review - cohort A",
      },
      {
        key: "_paes_linkeddemand_value",
        label: "Linked Demand",
        type: "lookup",
        required: true,
        placeholder: "Select demand",
        lookup: { moduleKey: "demand", bindKey: "paes_LinkedDemand" },
      },
      {
        key: "_paes_linkedsupply_value",
        label: "Linked Supply",
        type: "lookup",
        required: true,
        placeholder: "Select supply",
        lookup: { moduleKey: "supply", bindKey: "paes_LinkedSupply" },
      },
      { key: "paes_readinessstatus", label: "Readiness Status", required: true, options: readinessStatusOptions, placeholder: "Select readiness status" },
      { key: "paes_skillsmatch", label: "Skills Match", required: true, minLength: 2, maxLength: 120, placeholder: "Strong, moderate, partial" },
      { key: "paes_experiencematch", label: "Experience Match", required: true, minLength: 2, maxLength: 120, placeholder: "Meets minimum delivery requirement" },
      { key: "paes_qualificationstatus", label: "Qualification Status", required: true, options: yesNoPartialOptions, placeholder: "Select qualification status" },
      { key: "paes_certificationstatus", label: "Certification Status", required: true, options: yesNoPartialOptions, placeholder: "Select certification status" },
      {
        key: "paes_trainingstatus",
        label: "Training Status",
        required: true,
        options: [
          { label: "Not Started", value: "Not Started" },
          { label: "In Progress", value: "In Progress" },
          { label: "Completed", value: "Completed" },
        ],
        placeholder: "Select training status",
      },
      { key: "paes_keyrequirementsmet", label: "Key Requirements Met", required: true, options: yesNoPartialOptions, placeholder: "Select outcome" },
      { key: "paes_dateupdated", label: "Date Updated", type: "date", required: true },
      { key: "paes_notes", label: "Notes", type: "textarea", maxLength: 500, placeholder: "Record readiness blockers, training plans, certification gaps, or evidence collected." },
    ],
  }),
  buildModule<BaseRecord>({
    key: "partners",
    label: "Partner Management",
    singularLabel: "Partner",
    path: "partners",
    icon: "building",
    tableName: "PAES Partner",
    entitySetName: "paes_paespartners",
    primaryIdField: "paes_paespartnerid",
    titleField: "name",
    columns: [
      { key: "paes_partnername" as keyof BaseRecord, label: "Partner" },
      { key: "paes_partnertype" as keyof BaseRecord, label: "Partner Type" },
      { key: "paes_region" as keyof BaseRecord, label: "Region" },
      { key: "paes_country" as keyof BaseRecord, label: "Country" },
      { key: "paes_status" as keyof BaseRecord, label: "Status" },
    ],
    detailFields: [
      { key: "paes_partnername" as keyof BaseRecord, label: "Partner Name" },
      { key: "paes_partnerid" as keyof BaseRecord, label: "Partner ID" },
      { key: "paes_partnertype" as keyof BaseRecord, label: "Partner Type" },
      { key: "paes_contactperson" as keyof BaseRecord, label: "Contact Person" },
      { key: "paes_email" as keyof BaseRecord, label: "Email" },
      { key: "paes_phone" as keyof BaseRecord, label: "Phone" },
      { key: "paes_country" as keyof BaseRecord, label: "Country" },
      { key: "paes_region" as keyof BaseRecord, label: "Region" },
      { key: "paes_status" as keyof BaseRecord, label: "Status" },
      { key: "paes_notes" as keyof BaseRecord, label: "Notes" },
    ],
    formFields: [
      { key: "paes_partnerid", label: "Partner ID", hidden: true, autoGenerate: { prefix: "PAR" } },
      { key: "paes_partnername", label: "Partner Name", required: true, minLength: 2, maxLength: 120, placeholder: "Employer, academy, or delivery partner" },
      { key: "paes_partnertype", label: "Partner Type", required: true, minLength: 2, maxLength: 80, placeholder: "Employer, training partner, certifying body" },
      { key: "paes_contactperson", label: "Contact Person", required: true, minLength: 2, maxLength: 120, placeholder: "Primary business contact" },
      { key: "paes_email", label: "Email", type: "email", required: true, placeholder: "partner@organization.com" },
      { key: "paes_phone", label: "Phone", type: "tel", required: true, minLength: 8, maxLength: 20, pattern: "^[+0-9()\\-\\s]{8,20}$", patternMessage: "Enter a valid phone number", placeholder: "+251 91 234 5678" },
      { key: "paes_country", label: "Country", required: true, minLength: 2, maxLength: 80, placeholder: "Country of operation" },
      { key: "paes_region", label: "Region", required: true, minLength: 2, maxLength: 80, placeholder: "Regional office or delivery hub" },
      {
        key: "paes_status",
        label: "Status",
        required: true,
        options: [
          { label: "Active", value: "Active" },
          { label: "Inactive", value: "Inactive" },
          { label: "Onboarding", value: "Onboarding" },
        ],
        placeholder: "Select status",
      },
      { key: "paes_notes", label: "Notes", type: "textarea", maxLength: 500, placeholder: "Commercial terms, delivery notes, escalation contacts, or service scope." },
    ],
  }),
  buildModule<BaseRecord>({
    key: "deployments",
    label: "Deployment Tracking",
    singularLabel: "Deployment",
    path: "deployments",
    icon: "map",
    tableName: "PAES Deployment",
    entitySetName: "paes_paesdeployments",
    primaryIdField: "paes_paesdeploymentid",
    titleField: "name",
    columns: [
      { key: "paes_deploymentname" as keyof BaseRecord, label: "Deployment" },
      { key: "paes_deploymentdate" as keyof BaseRecord, label: "Deployment Date" },
      { key: "paes_region" as keyof BaseRecord, label: "Region" },
      { key: "paes_numberdeployed" as keyof BaseRecord, label: "Number Deployed" },
      { key: "paes_deploymentstatus" as keyof BaseRecord, label: "Deployment Status" },
    ],
    detailFields: [
      { key: "paes_deploymentname" as keyof BaseRecord, label: "Deployment Name" },
      { key: "paes_deploymentid" as keyof BaseRecord, label: "Deployment ID" },
      { key: "paes_deploymentdate" as keyof BaseRecord, label: "Deployment Date" },
      { key: "paes_deploymentstatus" as keyof BaseRecord, label: "Deployment Status" },
      { key: "paes_region" as keyof BaseRecord, label: "Region" },
      { key: "paes_numberdeployed" as keyof BaseRecord, label: "Number Deployed" },
      { key: "paes_placementrevenue" as keyof BaseRecord, label: "Placement Revenue" },
      { key: "paes_notes" as keyof BaseRecord, label: "Notes" },
    ],
    formFields: [
      { key: "paes_deploymentid", label: "Deployment ID", hidden: true, autoGenerate: { prefix: "DEP" } },
      { key: "paes_deploymentname", label: "Deployment Name", required: true, minLength: 5, maxLength: 120, placeholder: "Outbound sales launch - wave 1" },
      {
        key: "_paes_linkeddemand_value",
        label: "Linked Demand",
        type: "lookup",
        required: true,
        placeholder: "Select demand",
        lookup: { moduleKey: "demand", bindKey: "paes_LinkedDemand" },
      },
      {
        key: "_paes_linkedsupply_value",
        label: "Linked Supply",
        type: "lookup",
        required: true,
        placeholder: "Select supply",
        lookup: { moduleKey: "supply", bindKey: "paes_LinkedSupply" },
      },
      {
        key: "_paes_linkedreadiness_value",
        label: "Linked Readiness",
        type: "lookup",
        required: true,
        placeholder: "Select readiness",
        lookup: { moduleKey: "readiness", bindKey: "paes_LinkedReadiness" },
      },
      {
        key: "_paes_partner_value",
        label: "Partner",
        type: "lookup",
        required: true,
        placeholder: "Select partner",
        lookup: { moduleKey: "partners", bindKey: "paes_Partner" },
      },
      { key: "paes_deploymentdate", label: "Deployment Date", type: "date", required: true },
      {
        key: "paes_deploymentstatus",
        label: "Deployment Status",
        required: true,
        options: [
          { label: "Planned", value: "Planned" },
          { label: "Active", value: "Active" },
          { label: "Completed", value: "Completed" },
        ],
        placeholder: "Select deployment status",
      },
      { key: "paes_region", label: "Region", required: true, minLength: 2, maxLength: 80, placeholder: "Country, city, or delivery region" },
      { key: "paes_numberdeployed", label: "Number Deployed", type: "number", required: true, min: 1, step: 1, placeholder: "0" },
      { key: "paes_placementrevenue", label: "Placement Revenue", type: "number", min: 0, step: 0.01, placeholder: "0.00" },
      { key: "paes_notes", label: "Notes", type: "textarea", maxLength: 500, placeholder: "Capture launch notes, placement issues, post-go-live risk, or partner follow-up actions." },
    ],
  }),
  buildModule<BaseRecord>({
    key: "learners",
    label: "Learners",
    singularLabel: "Learner",
    path: "learners",
    icon: "graduation",
    tableName: "PAES Learner",
    entitySetName: "paes_paeslearners",
    primaryIdField: "paes_paeslearnerid",
    titleField: "name",
    columns: [
      { key: "paes_learnername" as keyof BaseRecord, label: "Learner" },
      { key: "paes_email" as keyof BaseRecord, label: "Email" },
      { key: "paes_phone" as keyof BaseRecord, label: "Phone" },
      { key: "paes_region" as keyof BaseRecord, label: "Region" },
      { key: "paes_status" as keyof BaseRecord, label: "Status" },
    ],
    detailFields: [
      { key: "paes_learnername" as keyof BaseRecord, label: "Learner Name" },
      { key: "paes_learnerid" as keyof BaseRecord, label: "Learner ID" },
      { key: "paes_email" as keyof BaseRecord, label: "Email" },
      { key: "paes_phone" as keyof BaseRecord, label: "Phone" },
      { key: "paes_gender" as keyof BaseRecord, label: "Gender" },
      { key: "paes_dateofbirth" as keyof BaseRecord, label: "Date of Birth" },
      { key: "paes_region" as keyof BaseRecord, label: "Region" },
      { key: "paes_status" as keyof BaseRecord, label: "Status" },
      { key: "paes_notes" as keyof BaseRecord, label: "Notes" },
    ],
    formFields: [
      { key: "paes_learnerid", label: "Learner ID", hidden: true, autoGenerate: { prefix: "LRN" } },
      { key: "paes_learnername", label: "Learner Name", required: true, minLength: 2, maxLength: 120, placeholder: "Learner full name" },
      {
        key: "_paes_linkedsupply_value",
        label: "Linked Supply",
        type: "lookup",
        required: true,
        placeholder: "Select supply",
        lookup: { moduleKey: "supply", bindKey: "paes_LinkedSupply" },
      },
      {
        key: "_paes_linkedcourse_value",
        label: "Linked Course",
        type: "lookup",
        required: true,
        placeholder: "Select course",
        lookup: { moduleKey: "courses", bindKey: "paes_LinkedCourse" },
      },
      { key: "paes_email", label: "Email", type: "email", required: true, placeholder: "learner@domain.com" },
      { key: "paes_phone", label: "Phone", type: "tel", required: true, minLength: 8, maxLength: 20, pattern: "^[+0-9()\\-\\s]{8,20}$", patternMessage: "Enter a valid phone number", placeholder: "+251 91 234 5678" },
      {
        key: "paes_gender",
        label: "Gender",
        required: true,
        options: [
          { label: "Female", value: "Female" },
          { label: "Male", value: "Male" },
          { label: "Other", value: "Other" },
        ],
        placeholder: "Select gender",
      },
      { key: "paes_dateofbirth", label: "Date of Birth", type: "date" },
      { key: "paes_region", label: "Region", required: true, minLength: 2, maxLength: 80, placeholder: "Country, city, or delivery region" },
      { key: "paes_status", label: "Status", required: true, options: commonStatusOptions, placeholder: "Select status" },
      { key: "paes_notes", label: "Notes", type: "textarea", maxLength: 500, placeholder: "Learner follow-up, safeguarding remarks, readiness notes, or placement support actions." },
    ],
  }),
  buildModule<BaseRecord>({
    key: "courses",
    label: "Courses",
    singularLabel: "Course",
    path: "courses",
    icon: "book",
    tableName: "PAES Course",
    entitySetName: "paes_paescourses",
    primaryIdField: "paes_paescourseid",
    titleField: "name",
    columns: [
      { key: "paes_coursename" as keyof BaseRecord, label: "Course" },
      { key: "paes_category" as keyof BaseRecord, label: "Category" },
      { key: "paes_skillcategory" as keyof BaseRecord, label: "Skill Category" },
      { key: "paes_deliverytype" as keyof BaseRecord, label: "Delivery Type" },
      { key: "paes_status" as keyof BaseRecord, label: "Status" },
    ],
    detailFields: [
      { key: "paes_coursename" as keyof BaseRecord, label: "Course Name" },
      { key: "paes_courseid" as keyof BaseRecord, label: "Course ID" },
      { key: "paes_category" as keyof BaseRecord, label: "Category" },
      { key: "paes_skillcategory" as keyof BaseRecord, label: "Skill Category" },
      { key: "paes_deliverytype" as keyof BaseRecord, label: "Delivery Type" },
      { key: "paes_duration" as keyof BaseRecord, label: "Duration" },
      { key: "paes_price" as keyof BaseRecord, label: "Price" },
      { key: "paes_status" as keyof BaseRecord, label: "Status" },
      { key: "paes_notes" as keyof BaseRecord, label: "Notes" },
    ],
    formFields: [
      { key: "paes_courseid", label: "Course ID", hidden: true, autoGenerate: { prefix: "CRS" } },
      { key: "paes_coursename", label: "Course Name", required: true, minLength: 4, maxLength: 120, placeholder: "Digital sales readiness bootcamp" },
      { key: "paes_category", label: "Category", required: true, minLength: 2, maxLength: 80, placeholder: "Technical, business, employability" },
      { key: "paes_skillcategory", label: "Skill Category", required: true, minLength: 2, maxLength: 80, placeholder: "Digital sales, nursing support, software QA" },
      {
        key: "paes_deliverytype",
        label: "Delivery Type",
        required: true,
        options: [
          { label: "Online", value: "Online" },
          { label: "Hybrid", value: "Hybrid" },
          { label: "In Person", value: "In Person" },
        ],
        placeholder: "Select delivery type",
      },
      { key: "paes_duration", label: "Duration", required: true, minLength: 2, maxLength: 80, placeholder: "6 weeks, 120 hours, 3 weekends" },
      { key: "paes_price", label: "Price", type: "number", min: 0, step: 0.01, placeholder: "0.00" },
      { key: "paes_status", label: "Status", required: true, options: commonStatusOptions, placeholder: "Select status" },
      { key: "paes_notes", label: "Notes", type: "textarea", maxLength: 500, placeholder: "Delivery language, venue, cohort size assumptions, or certification alignment notes." },
    ],
  }),
  buildModule<BaseRecord>({
    key: "payments",
    label: "Payments",
    singularLabel: "Payment",
    path: "payments",
    icon: "wallet",
    tableName: "PAES Payment",
    entitySetName: "paes_paespayments",
    primaryIdField: "paes_paespaymentid",
    titleField: "name",
    columns: [
      { key: "paes_paymentreference" as keyof BaseRecord, label: "Payment Reference" },
      { key: "paes_paymentdate" as keyof BaseRecord, label: "Payment Date" },
      { key: "paes_amount" as keyof BaseRecord, label: "Amount" },
      { key: "paes_revenuestream" as keyof BaseRecord, label: "Revenue Stream" },
      { key: "paes_paymentstatus" as keyof BaseRecord, label: "Payment Status" },
    ],
    detailFields: [
      { key: "paes_paymentreference" as keyof BaseRecord, label: "Payment Reference" },
      { key: "paes_paymentid" as keyof BaseRecord, label: "Payment ID" },
      { key: "paes_paymentdate" as keyof BaseRecord, label: "Payment Date" },
      { key: "paes_amount" as keyof BaseRecord, label: "Amount" },
      { key: "paes_paymenttype" as keyof BaseRecord, label: "Payment Type" },
      { key: "paes_revenuestream" as keyof BaseRecord, label: "Revenue Stream" },
      { key: "paes_paymentstatus" as keyof BaseRecord, label: "Payment Status" },
      { key: "paes_notes" as keyof BaseRecord, label: "Notes" },
    ],
    formFields: [
      { key: "paes_paymentid", label: "Payment ID", hidden: true, autoGenerate: { prefix: "PAY" } },
      {
        key: "paes_paymentreference",
        label: "Payment Reference",
        required: true,
        minLength: 4,
        maxLength: 80,
        placeholder: "Invoice or receipt reference",
      },
      {
        key: "_paes_linkeddeployment_value",
        label: "Linked Deployment",
        type: "lookup",
        placeholder: "Select deployment",
        lookup: { moduleKey: "deployments", bindKey: "paes_LinkedDeployment" },
      },
      {
        key: "_paes_linkedlearner_value",
        label: "Linked Learner",
        type: "lookup",
        placeholder: "Select learner",
        lookup: { moduleKey: "learners", bindKey: "paes_LinkedLearner" },
      },
      { key: "paes_paymentdate", label: "Payment Date", type: "date", required: true },
      { key: "paes_amount", label: "Amount", type: "number", required: true, min: 0.01, step: 0.01, placeholder: "0.00" },
      {
        key: "paes_paymenttype",
        label: "Payment Type",
        required: true,
        options: [
          { label: "Invoice", value: "Invoice" },
          { label: "Collection", value: "Collection" },
          { label: "Adjustment", value: "Adjustment" },
        ],
        placeholder: "Select payment type",
      },
      {
        key: "paes_revenuestream",
        label: "Revenue Stream",
        required: true,
        options: [
          { label: "Deployment", value: "Deployment" },
          { label: "Learning", value: "Learning" },
          { label: "Event", value: "Event" },
          { label: "Certification", value: "Certification" },
        ],
        placeholder: "Select revenue stream",
      },
      {
        key: "paes_paymentstatus",
        label: "Payment Status",
        required: true,
        options: [
          { label: "Pending", value: "Pending" },
          { label: "Paid", value: "Paid" },
          { label: "Overdue", value: "Overdue" },
        ],
        placeholder: "Select payment status",
      },
      { key: "paes_notes", label: "Notes", type: "textarea", maxLength: 500, placeholder: "Payment notes, remittance references, or follow-up actions." },
    ],
  }),
  buildModule<BaseRecord>({
    key: "events",
    label: "Events",
    singularLabel: "Event",
    path: "events",
    icon: "calendar",
    tableName: "PAES Event",
    entitySetName: "paes_paesevents",
    primaryIdField: "paes_paeseventid",
    titleField: "name",
    columns: [
      { key: "paes_eventname" as keyof BaseRecord, label: "Event" },
      { key: "paes_eventdate" as keyof BaseRecord, label: "Event Date" },
      { key: "paes_eventtype" as keyof BaseRecord, label: "Event Type" },
      { key: "paes_location" as keyof BaseRecord, label: "Location" },
      { key: "paes_status" as keyof BaseRecord, label: "Status" },
    ],
    detailFields: [
      { key: "paes_eventname" as keyof BaseRecord, label: "Event Name" },
      { key: "paes_eventid" as keyof BaseRecord, label: "Event ID" },
      { key: "paes_eventdate" as keyof BaseRecord, label: "Event Date" },
      { key: "paes_eventtype" as keyof BaseRecord, label: "Event Type" },
      { key: "paes_location" as keyof BaseRecord, label: "Location" },
      { key: "paes_organizer" as keyof BaseRecord, label: "Organizer" },
      { key: "paes_capacity" as keyof BaseRecord, label: "Capacity" },
      { key: "paes_costperparticipant" as keyof BaseRecord, label: "Cost Per Participant" },
      { key: "paes_totalregistrations" as keyof BaseRecord, label: "Total Registrations" },
      { key: "paes_totalattendance" as keyof BaseRecord, label: "Total Attendance" },
      { key: "paes_totalrevenue" as keyof BaseRecord, label: "Total Revenue" },
      { key: "paes_status" as keyof BaseRecord, label: "Status" },
      { key: "paes_notes" as keyof BaseRecord, label: "Notes" },
    ],
    formFields: [
      { key: "paes_eventid", label: "Event ID", hidden: true, autoGenerate: { prefix: "EVT" } },
      {
        key: "paes_eventname",
        label: "Event Name",
        required: true,
        minLength: 4,
        maxLength: 120,
        placeholder: "Regional talent and employer forum",
        description: "Create the event record even if you only want to track summary totals and not individual attendees.",
      },
      { key: "paes_eventdate", label: "Event Date", type: "date", required: true },
      {
        key: "paes_eventtype",
        label: "Event Type",
        required: true,
        options: [
          { label: "Workshop", value: "Workshop" },
          { label: "Seminar", value: "Seminar" },
          { label: "Career Fair", value: "Career Fair" },
        ],
        placeholder: "Select event type",
      },
      { key: "paes_location", label: "Location", required: true, minLength: 2, maxLength: 120, placeholder: "City, venue, or delivery hub" },
      { key: "paes_organizer", label: "Organizer", required: true, minLength: 2, maxLength: 120, placeholder: "PAES team or partner name" },
      { key: "paes_capacity", label: "Capacity", type: "number", required: true, min: 1, step: 1, placeholder: "0" },
      { key: "paes_costperparticipant", label: "Cost Per Participant", type: "number", min: 0, step: 0.01, placeholder: "0.00" },
      {
        key: "paes_totalregistrations",
        label: "Total Registrations",
        type: "number",
        min: 0,
        step: 1,
        placeholder: "0",
        description: "Use this when you are tracking the event at summary level only.",
      },
      { key: "paes_totalattendance", label: "Total Attendance", type: "number", min: 0, step: 1, placeholder: "0" },
      { key: "paes_totalrevenue", label: "Total Revenue", type: "number", min: 0, step: 0.01, placeholder: "0.00" },
      { key: "paes_status", label: "Status", required: true, options: commonStatusOptions, placeholder: "Select status" },
      { key: "paes_notes", label: "Notes", type: "textarea", maxLength: 500, placeholder: "Audience, sponsor notes, target employers, or follow-up actions." },
    ],
  }),
  buildModule<BaseRecord>({
    key: "event-registrations",
    label: "Event Registrations",
    singularLabel: "Event Registration",
    path: "event-registrations",
    icon: "calendar",
    tableName: "PAES Event Registration",
    entitySetName: "paes_paeseventregistrations",
    primaryIdField: "paes_paeseventregistrationid",
    titleField: "name",
    columns: [
      { key: "paes_registrationname" as keyof BaseRecord, label: "Registration" },
      { key: "paes_registrationid" as keyof BaseRecord, label: "Registration ID" },
      { key: "paes_paymentstatus" as keyof BaseRecord, label: "Payment Status" },
      { key: "paes_attendancestatus" as keyof BaseRecord, label: "Attendance Status" },
      { key: "paes_amountpaid" as keyof BaseRecord, label: "Amount Paid" },
    ],
    detailFields: [
      { key: "paes_registrationname" as keyof BaseRecord, label: "Registration Name" },
      { key: "paes_registrationid" as keyof BaseRecord, label: "Registration ID" },
      { key: "paes_paymentstatus" as keyof BaseRecord, label: "Payment Status" },
      { key: "paes_attendancestatus" as keyof BaseRecord, label: "Attendance Status" },
      { key: "paes_amountpaid" as keyof BaseRecord, label: "Amount Paid" },
      { key: "paes_notes" as keyof BaseRecord, label: "Notes" },
    ],
    formFields: [
      { key: "paes_registrationid", label: "Registration ID", hidden: true, autoGenerate: { prefix: "REG" } },
      {
        key: "paes_registrationname",
        label: "Registration Name",
        required: true,
        minLength: 4,
        maxLength: 120,
        placeholder: "Event registration reference",
        description: "Only create this when you need participant-level attendance or payment tracking.",
      },
      {
        key: "_paes_linkedevent_value",
        label: "Linked Event",
        type: "lookup",
        required: true,
        placeholder: "Select event",
        lookup: { moduleKey: "events", bindKey: "paes_LinkedEvent" },
      },
      {
        key: "_paes_participant_value",
        label: "Participant",
        type: "lookup",
        required: true,
        placeholder: "Select learner",
        lookup: { moduleKey: "learners", bindKey: "paes_Participant" },
      },
      {
        key: "paes_paymentstatus",
        label: "Payment Status",
        required: true,
        options: [
          { label: "Pending", value: "Pending" },
          { label: "Paid", value: "Paid" },
        ],
        placeholder: "Select payment status",
      },
      {
        key: "paes_attendancestatus",
        label: "Attendance Status",
        required: true,
        options: [
          { label: "Registered", value: "Registered" },
          { label: "Attended", value: "Attended" },
          { label: "No Show", value: "No Show" },
        ],
        placeholder: "Select attendance status",
      },
      { key: "paes_amountpaid", label: "Amount Paid", type: "number", min: 0, step: 0.01, placeholder: "0.00" },
      { key: "paes_notes", label: "Notes", type: "textarea", maxLength: 500, placeholder: "Registration notes, attendance remarks, or payment follow-up." },
    ],
  }),
  buildModule<BaseRecord>({
    key: "certifications",
    label: "Certifications",
    singularLabel: "Certification",
    path: "certifications",
    icon: "book",
    tableName: "PAES Certification",
    entitySetName: "paes_paescertifications",
    primaryIdField: "paes_paescertificationid",
    titleField: "name",
    columns: [
      { key: "paes_certificationname" as keyof BaseRecord, label: "Certification" },
      { key: "paes_certificationid" as keyof BaseRecord, label: "Certification ID" },
      { key: "paes_certifyingbody" as keyof BaseRecord, label: "Certifying Body" },
      { key: "paes_skillcategory" as keyof BaseRecord, label: "Skill Category" },
      { key: "paes_status" as keyof BaseRecord, label: "Status" },
    ],
    detailFields: [
      { key: "paes_certificationname" as keyof BaseRecord, label: "Certification Name" },
      { key: "paes_certificationid" as keyof BaseRecord, label: "Certification ID" },
      { key: "paes_certifyingbody" as keyof BaseRecord, label: "Certifying Body" },
      { key: "paes_skillcategory" as keyof BaseRecord, label: "Skill Category" },
      { key: "paes_datestarted" as keyof BaseRecord, label: "Date Started" },
      { key: "paes_datecompleted" as keyof BaseRecord, label: "Date Completed" },
      { key: "paes_cost" as keyof BaseRecord, label: "Cost" },
      { key: "paes_revenue" as keyof BaseRecord, label: "Revenue" },
      { key: "paes_paymentstatus" as keyof BaseRecord, label: "Payment Status" },
      { key: "paes_status" as keyof BaseRecord, label: "Status" },
      { key: "paes_notes" as keyof BaseRecord, label: "Notes" },
    ],
    formFields: [
      { key: "paes_certificationid", label: "Certification ID", hidden: true, autoGenerate: { prefix: "CER" } },
      { key: "paes_certificationname", label: "Certification Name", required: true, minLength: 4, maxLength: 120, placeholder: "Pearson customer service certification" },
      {
        key: "_paes_candidateorsupply_value",
        label: "Candidate or Supply",
        type: "lookup",
        required: true,
        placeholder: "Select supply",
        lookup: { moduleKey: "supply", bindKey: "paes_CandidateorSupply" },
      },
      {
        key: "_paes_linkeddemand_value",
        label: "Linked Demand",
        type: "lookup",
        placeholder: "Select demand",
        lookup: { moduleKey: "demand", bindKey: "paes_LinkedDemand" },
      },
      { key: "paes_certifyingbody", label: "Certifying Body", required: true, minLength: 2, maxLength: 120, placeholder: "Pearson, Prometric, NHA" },
      { key: "paes_skillcategory", label: "Skill Category", required: true, minLength: 2, maxLength: 80, placeholder: "Healthcare, ICT, customer support" },
      { key: "paes_datestarted", label: "Date Started", type: "date" },
      { key: "paes_datecompleted", label: "Date Completed", type: "date" },
      { key: "paes_cost", label: "Cost", type: "number", min: 0, step: 0.01, placeholder: "0.00" },
      { key: "paes_revenue", label: "Revenue", type: "number", min: 0, step: 0.01, placeholder: "0.00" },
      {
        key: "paes_paymentstatus",
        label: "Payment Status",
        required: true,
        options: [
          { label: "Pending", value: "Pending" },
          { label: "Paid", value: "Paid" },
        ],
        placeholder: "Select payment status",
      },
      {
        key: "paes_status",
        label: "Status",
        required: true,
        options: [
          { label: "Not Started", value: "Not Started" },
          { label: "In Progress", value: "In Progress" },
          { label: "Completed", value: "Completed" },
        ],
        placeholder: "Select status",
      },
      { key: "paes_notes", label: "Notes", type: "textarea", maxLength: 500, placeholder: "Exam center, pending documents, coaching support, or compliance notes." },
    ],
  }),
];
